### ISSUE TITLE
Creation and Research of Figma Documentation 

### ISSUE THREAD

**Issue by smalinow** [xlab-classes/cse442-spring2022-team-init-d#2]
**Acceptance Test**

*Test 1*

1. Go to the GitHub page for the init.d team

2. Navigate to the folder named docs/

3. Verify that there is a file called Figma Documentation.md

4. Open Figma Documentation.md

5. Verify that the contents of Figma Documentation.md include links to relevant information with explanations about what each link goes to.

**Comment by FarhanTawsifChowdhury** [comment]
Figma documentation submited on docs folder.
